### ISSUE TITLE
Hablate white!

### ISSUE THREAD

**Issue by elvismdev** [alej4ndro-cm/About-Me#1]
Tu si suena! 😂

**Comment by a13jndro** [comment]
Me senté de nuevo en un banco roto,
Para darme DE cuenta que me faltabas hoy,
Casi estallo en pedazos al darme cuenta,
Que me faltaba algo, 
Me faltabas tu!

Yo te busco, yo te espero, quiero verte junto a mi,
Para no estallar en pedazos,
Porque hoy me faltas tu, me faltas tu, me faltas tu...
